name: wolf_im
description: "OpenIM is not just another chat application; it's an innovative open-source instant messaging solution specifically designed for developers. Unlike standalone applications like Telegram, Signal, and Rocket.Chat that provide complete user interfaces and backend services for general users, OpenIM offers a powerful backend and SDK tailored for seamless integration into your own applications."
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ^3.8.1

workspace:
  - modules/flutter_openim_sdk_ffi

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8

  # 便于结构比较
  equatable: ^2.0.7

  # 数据与持久化
  dio: ^5.4.3+1 # 网络请求
  shared_preferences: ^2.5.3 # xml 固化
  jwt_decoder: ^2.0.1 # jwt 解析
  path_provider: ^2.1.5  # 路径

  flutter_quill: ^11.0.0-dev.21

  # 添加图标生成工具
  flutter_launcher_icons: ^0.14.4

  # fx
  fx_boot_starter:
    path: modules/fx/fx_boot_starter
  fx_go_router_ext:
    path: modules/fx/fx_go_router_ext
  fx_platform_adapter:
    path: modules/fx/fx_platform_adapter
  fx_trace:
    path: modules/fx/fx_trace
  flame_ext:
    path: modules/fx/flame_ext
  fx_env:
    path: modules/fx/fx_env
  fx_string:
    path: modules/fx/fx_string

  # tolyui
  tolyui:
    path: modules/toly_ui/tolyui
  tolyui_navigation:
    path: modules/toly_ui/tolyui_navigation
  tolyui_meta:
    path: modules/toly_ui/tolyui_meta
  tolyui_feedback:
    path: modules/toly_ui/tolyui_feedback
  tolyui_color:
    path: modules/toly_ui/tolyui_color
  tolyui_image:
    path: modules/toly_ui/tolyui_image
  tolyui_message:
    path: modules/toly_ui/tolyui_message
  tolyui_refresh:
    path: modules/toly_ui/tolyui_refresh
  tolyui_rich_input:
    path: modules/toly_ui/tolyui_rich_input
  tolyui_rx_layout:
    path: modules/toly_ui/tolyui_rx_layout
  tolyui_skeleton:
    path: modules/toly_ui/tolyui_skeleton
  wrapper:
    path: modules/toly_ui/wrapper

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  intl: 0.20.2

flutter:
  uses-material-design: true
  generate: true

  assets:
    - assets/images/
    - assets/data/
    #    - assets/data/web/
    - assets/images/head_icon/
    - assets/images/widgets/
    - assets/flutter.db
    - assets/version.json

  fonts: # 配置字体，可配置多个，支持ttf和otf,ttc等字体资源
    - family: TolyIcon
      fonts:
        - asset: assets/iconfont/toly_icon.ttf
    - family: BalooBhai2 #字体名
      fonts:
        - asset: assets/fonts/BalooBhai2-Regular.ttf
    - family: ComicNeue #字体名
      fonts:
        - asset: assets/fonts/ComicNeue-Regular.ttf
    - family: RegularScript
      fonts:
        - asset: assets/fonts/RegularScript.ttf
    - family: WorkSans
      fonts:
        - asset: assets/fonts/WorkSans-Regular.ttf
    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-Regular.ttf

toly:
  icon:
    src_zip: ''
    assets_dir: 'assets/iconfont'
    file_dist: 'packages/app/lib/app/res/toly_icon.dart'

flutter_icons:
  # flutter pub run flutter_launcher_icons
  image_path: "assets/icons/app_icon.png"

  # 移动端配置
  android: true  # 自动生成Android图标
  ios: true      # 自动生成iOS图标

  # 桌面端配置（需要额外设置）
  windows:
    generate: true
    image_path: "assets/icons/app_icon.png"
    icon_size: 48  # Windows图标基础尺寸（会自动生成不同尺寸）
  macos:
    generate: true
    image_path: "assets/icons/app_icon.png"
  linux:
    generate: true
    image_path: "assets/icons/app_icon.png"

